rancher/dartboard

darts/aws_full.yaml, darts/aws_simple.yaml, darts/k3d_full.yaml, internal/dart/recipe.go, tofu/main/aws/main.tf, tofu/main/aws/variables.tf
This:
1.  uniforms darts: _full darts should contain all defaults commented out, but they didn't
2. bumps Rancher to 2.9.1 for all of them
3. adds an aws_simple.yaml dart which is meant to be as bare-bones, fool-proof as possible
Best reviewed commit-by-commit
CI failures addressed in https://github.com/rancher/dartboard/pull/4
=> AWS dart fixes

cmd/dartboard/subcommands/deploy.go, internal/kubectl/kubectl.go
Previous code did not wait after Rancher installation to install Rancher Monitoring.
Since 2.9, some Rancher components need to be ready or the installation will fail, eg.:
```
2024/08/29 14:50:01 chart rancher-monitoring: failed pre-install: warning: Hook pre-install rancher-monitoring/templates/alertmanager/secret.yaml failed: 1 error occurred:
* Internal error occurred: failed calling webhook "rancher.cattle.io.secrets": failed to call webhook: Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/mutation/secrets?timeout=15s": no endpoints available fo
r service "rancher-webhook"
```
More components can be added if needed in the same way (eg. `cattle-fleet-system/gitjob` or `cattle-provisioning-capi-system/capi-controller-manager`, which did not pop up in my own tests but …
=> Fix Rancher monitoring deployment errors

k6/api_benchmark.js
Before the only option was to benchmark all pages.
=> k6: api_benchmark: allow to benchmark one page only

k6/change_config_maps.js, k6/k8s.js
Previous code had several issues that resulted in the change rate not being correct:
1. the RATE parameter was not actually read from environment variables 🤦 🤦 🤦 
2. it did not take into account that every k6 iteration we are doing two operations (one creation and one deletion)
3. it did not use the `constant-arrival-rate` executor, which meant the rate was not actually guaranteed by k6 🤦 
4. creation might have caused unintended retries, which would skew the rate
This PR addresses all of the above.
=> k6/change_config_maps: fix rate

tofu/modules/rke2/wait_for_k8s.sh
Prevents the following error:
```
* Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": failed to call webhook: Post "https://rke2-ingress-nginx-controller-admission.kube-system.svc:443/networking/v1/ingresses?timeout=10s": no endpoints available for service "rke2-ingress-nginx-controller-admission"
```
=> rke2: wait until ingress is up

tofu/modules/ssh_access/main.tf
Address a bug where tunnels were not created in case the bastion host username was different from the one for the VM.
=> ssh: use correct ssh username for the bastion host

cmd/dartboard/subcommands/deploy.go
This fixes the following error:
```
Release "rancher-monitoring" does not exist. Installing it now. 2024/11/14 13:21:01 chart rancher-monitoring: Error: 5 errors occurred:
* Deployment in version "v1" cannot be handled as a Deployment: json: cannot unmarshal bool into Go struct field PodSpec.spec.template.spec.nodeSelector of type string
* Deployment in version "v1" cannot be handled as a Deployment: json: cannot unmarshal bool into Go struct field PodSpec.spec.template.spec.nodeSelector of type string
* Deployment in version "v1" cannot be handled as a Deployment: json: cannot unmarshal bool into Go struct field PodSpec.spec.template.spec.nodeSelector of type string
* Deployment in version "v1" cannot be handled as a Deployment: json: cannot unmarshal bool into Go struct field …
```
=> bugfix: regression in helm install of Rancher monitoring

internal/kubectl/kubectl.go
This makes it easier to debug k6 scripts by outputting in logs the equivalent k6 commandline for a local k6 run.
Currently dartboard runs `k6` from a container in the tester cluster, by first copying over `k6/` and `k6/lib` files as ConfigMaps via `helm`:
```
2024/11/14 15:52:33 Installing chart "tester/k6-files" (charts/k6-files)
2024/11/14 15:52:33 Running command:
.bin/helm --kubeconfig=/Users/SMOIOLI/synced/repos/dartboard/tofu/main/aws/config/tester.yaml upgrade --install --namespace=tester k6-files charts/k6-files --create-namespace
Release "k6-files" does not exist. Installing it now.
NAME: k6-files
LAST DEPLOYED: Thu Nov 14 15:52:36 2024
NAMESPACE: tester
STATUS: deployed
REVISION: 1
TEST SUITE: None
```
And then running `k6` via `kubectl` from a container in a pod in the tester …
=> add debug log line to run k6 directly

internal/tofu/tofu.go
Pull #16 introduced a regression which broke destroy
=> bugfix: restore variables in destroy subcommand

cmd/dartboard/subcommands/deploy.go, cmd/dartboard/subcommands/load.go, internal/kubectl/kubectl.go, internal/tofu/tofu.go, tofu/main/aws/outputs.tf, tofu/main/azure/outputs.tf, tofu/main/k3d/outputs.tf, tofu/main/openstack/outputs.tf, tofu/main/ssh/outputs.tf, tofu/modules/aws_k3s/outputs.tf, tofu/modules/aws_rke2/outputs.tf, tofu/modules/azure_aks/output.tf, tofu/modules/azure_k3s/output.tf, tofu/modules/azure_rke2/output.tf, tofu/modules/k3d_k3s/outputs.tf, tofu/modules/k3s/outputs.tf, tofu/modules/openstack_k3s/outputs.tf, tofu/modules/rke2/outputs.tf, tofu/modules/ssh_k3s/outputs.tf
This builds on top of #26 to make it more useful.
Specifically, it substitutes k6's `-e BASE_URL=...` parameter with the "correct" base url for k6 to connect to, which is not trivial because depending on the situation and the backend it might mean:
- the Rancher address - possibly an alias if a tunnel is used (instead of the private one) or a public one
- the Kubernetes address - possibly an alias if the tunnel is used (instead of the private one) or a public one
In order to use the right address, I had to expand a bit the format of tofu module outputs to clarify which-is-which among Rancher/Kubernetes/public/private/tunnelled addresses. Hence this patch is way bigger than it should be.
Nevertheless I tested it locally and it seems to work well in the various cases.
I am open to fix up …
=> Add debug log line to run k6 directly: refined

darts/aws_full.yaml, tofu/main/aws/locals.tf, tofu/main/aws/variables.tf
The AWS backend got inadvertently broken by #19 
go code expects specific cluster names: upstream, tester, and downstream + a suffix
Current AWS code returns names like upstream-0 or tester-1 which result in dartboard deploy failing.
This PR removes the ability to set a prefix and adds suffix numbers only to downstream to keep the contract with the go part of the code.
Tested manually on AWS.
=> Unbreak AWS cluster naming

cmd/dartboard/subcommands/deploy.go, internal/tofu/tofu.go, tofu/main/aws/outputs.tf, tofu/main/azure/outputs.tf, tofu/main/k3d/outputs.tf, tofu/main/openstack/outputs.tf, tofu/main/ssh/outputs.tf
dartboard offers an option to set "monitoring" taints and node selectors to force all monitoring workloads to a specific node.
Tofu code made this parametric for each cluster at some point, while Go code stuck with an earlier assumption where all k3d clusters did not use this, and all others did.
This patch corrects that outdated assumption and makes go code follow Tofu parameters.
=> bugfix: set monitoring taints correctly

cmd/dartboard/subcommands/deploy.go
Adds an extra waiting step to rancher-webhook downstream.
In some situations (tested k3d locally) the rancher-monitoring chart is installed earlier than cluster import is completed, and the webhook fails because its endpoint is not yet ready.
=> Bugfix: wait for webhook to be ready downstream as well

cmd/dartboard/subcommands/deploy.go, darts/aws.yaml, darts/azure.yaml, darts/k3d.yaml, internal/dart/recipe.go, internal/helm/helm.go
By setting a yaml-formatted text at `chart_variables.rancher_values` inside a Dartfile.
=> Add support for specifying arbitrary helm values for installing Rancher

.gitignore, README.md, tofu/main/aws/main.tf, tofu/main/aws/variables.tf, tofu/modules/aws/network/data.tf, tofu/modules/aws/network/main.tf, tofu/modules/aws/network/outputs.tf, tofu/modules/aws/network/variables.tf, tofu/modules/generic/k3s/variables.tf, tofu/modules/generic/rke2/variables.tf, tofu/modules/generic/test_environment/variables.tf
- Modifies `.gitignore` to account for new directory structure and future `tofu/` structure changes
- Updates the README with details on what needs to be manually configured/setup before BYO AWS VPC is usable
- Adds a new input var, and some data sources to enable BYO AWS VPC functionality
- The aws/network module defaults to creating the full network stack if `var.existing_vpc_name` is not passed in
- Added explicit types to multiple number variables as the latest version of open tofu doesn't seem to parse them as intended (without type hints)
=> "Bring Your Own" AWS VPC functionality

tofu/main/k3d/terraform.tf
After [upgrading the k3d dependency](https://github.com/moio/terraform-provider-k3d/pull/1), the newer version of k3d [brings support for recent k3s versions](https://github.com/k3d-io/k3d/pull/1479).
=> Upgrade terraform-provider-k3d to support newer versions of k3s

tofu/main/k3d/main.tf, tofu/main/k3d/terraform.tf
The new version of (see #40) seems to include a new "fix" for configuring DNS, that breaks the setup in my environment. https://github.com/k3d-io/k3d/pull/1492 disables that behavior for `host` network modes, which is not the case for dartboard, as it creates a dedicated network.
=> Fix networking problems after upgrading K3D

k6/create_k8s_resources.js
Part of the work for an upcoming kine investigation benchmark.
- fixes a bug where empty configmaps were creating instead of having the defined content
- makes the script optionally parametric by namespace, data size, and vus. By default nothing changes
=> k6/create_k8s_resources: script improvements

internal/kubectl/kubectl.go
This prevents the following error at `dartboard deploy` time:
```sh
2025/06/06 13:09:06 Import downstream clusters
2025/06/06 13:09:06 Running command:
.bin/kubectl --kubeconfig=/Users/SMOIOLI/synced/repos/dartboard/tofu/main/k3d/default_config/upstream.yaml get services --all-namespaces -o 'jsonpath={.items[0].status.loadBalancer.ingress[0]}'
2025/06/06 13:09:07 Running equivalent of:
./bin/k6 run -e [...]
2025/06/06 13:09:07 Running command:
.bin/kubectl --kubeconfig=/Users/SMOIOLI/synced/repos/dartboard/tofu/main/k3d/default_config/tester.yaml run k6 --http-debug=full [...]:
error: unknown flag: --http-debug
See 'kubectl run --help' for usage.
```
The problem is the flag was added to the kubectl run line, which accepts `k6` as the container name, but does not automatically pass options …
=> bugfix: kubectl run does not have --http-debug

tofu/modules/aws/network/variables.tf
OOM kills of SSH have been observed when deploying 100 clusters, the default (2 GiB of RAM) is definitely too little. Bumping to 8
=> bugfix: allow for a larger bastion to accommodate larger setups

k6/crds/create_crds.js, k6/crds/delete_crds.js, k6/crds/get_crds.js, k6/crds/load_crds.js, k6/crds/update_crds.js, k6/crds/update_destructive_crds.js, k6/rancher/rancher_utils.js, k6/schemas/verify_schema_definitions.js, k6/schemas/verify_schemas.js, k6/tests/tokens.js
This function used to return a bool, but now it returns the full response. This allows us some more flexibility in how we use it, while maintaining the previous capability to check the status returned a 200. This change will also allow us to inspect the other fields of the response object, such as the cookies; which we can then extract to login as multiple different users at the same time.
=> Update k6 login() func and all k6 scripts that use it

tofu/modules/generic/rke2/install_rke2.sh
According to 
* https://www.suse.com/support/kb/doc/?id=000021093
* https://www.suse.com/support/kb/doc/?id=000021322
The syntax for including a custom config is a bit different:
```
kubelet-arg:
- "--config=/etc/kubernetes/kubeletconfig.yml"
```
I could verify that after this change the node has the desired maxPods in its manifest and in the config file:
```
maxPods: 300
```
=> Fix inclusion of custom rke2 config for maxPods

charts/k6-files/templates/configmap.yaml
After #57, I was getting some errors during setup due to some files missing when running the k6 scripts. I traced it down to the `k6-test-files`, which is mounted as a volume into the k6 container, missing some files due to the new file structure.
```
ERRO[0000] The moduleSpecifier "k6/rancher_setup.js" couldn't be found on local disk.
```
<details>
<summary>Comparisson of files included in the ConfigMap</summary>
* Before these changes:
```
- k8s_api_benchmark.js
- js-yaml-4.1.0.mjs
- k6-summary-0.0.2.js
- papaparse-5.3.2.js
- url-1.0.0.js
```
* After these changes:
```
- api_benchmark.js
- change_config_maps.js
- crd_utils.js
- create_crds.js
- create_k8s_resources.js
- create_projects.js
- create_roles_users.js
- delete_crds.js
- get_crds.js
- js-yaml-4.1.0.mjs
- k6-summary-0.0.2.js
- …
```
=> Fix k6-test-files ConfigMap misssing some files

k6/namespaces/namespace_utils.js, k6/projects/project_utils.js, k6/rancher/rancher_diagnostics.js, k6/rancher/rancher_rolebindings_utils.js, k6/rancher/rancher_users_utils.js, k6/rancher/rancher_utils.js, k6/tests/k6_with_env.sh, k6/tests/load_projects_rbac.js
**NOTE:** This PR was mistakenly opened out of order, please review PR #85 first
- Adds various utils for:
- namespaces
- projects
- rolebindings
- users
- general rancher utils
- Adds robust metrics tracking support for the APIs tracked on the `rancher/diagnostics` page
The `load_projects_rbac.js` script was used for the testing of https://github.com/rancher/rancher/issues/50484 and its backports
Resolves https://github.com/rancher/dartboard/issues/52
Resolves https://github.com/rancher/dartboard/issues/75
=> Add load test for projects + namespaces

cmd/dartboard/subcommands/deploy.go, darts/aws.yaml, darts/azure.yaml, darts/harvester.yaml, darts/k3d.yaml, internal/dart/recipe.go
Adds an optional override field to Dart files for changing the URL used to pull Rancher App Charts from.
Integrates both `extra_environment_variables` and `rancher_values` from Dart files into the values passed to the `chartInstall(...)` call for Rancher.
Updates example Darts to include examples for both `extra_environment_variables` and `rancher_values`
Closes #78
=> Add override option to Dart files for rancher charts repo

docs/20250709 - Fleet Standalone 5000 Clusters.md
Split the scripts into a different branch, which is not intended to be merged into main: https://github.com/manno/dartboard/blob/20250709_fleet_standalone_5000_clusters_scripts/docs/20250709%20-%20Fleet%20Standalone%205000%20Clusters/
Will push this branch to `rancher/dartboard`, to make the links work, later.
=> Add setup docs for 5000 cluster fleet setup with k3k

tofu/main/aws/main.tf, tofu/main/aws/terraform.tf, tofu/main/aws/variables.tf, tofu/modules/aws/network/main.tf, tofu/modules/aws/network/outputs.tf, tofu/modules/aws/network/variables.tf, tofu/modules/aws/node/main.tf, tofu/modules/aws/node/outputs.tf, tofu/modules/aws/node/variables.tf, tofu/modules/generic/k3s/install_k3s.sh, tofu/modules/generic/k3s/main.tf, tofu/modules/generic/k3s/outputs.tf, tofu/modules/generic/k3s/variables.tf, tofu/modules/generic/node/outputs.tf, tofu/modules/generic/rke2/install_rke2.sh, tofu/modules/generic/rke2/main.tf, tofu/modules/generic/rke2/outputs.tf, tofu/modules/generic/rke2/variables.tf, tofu/modules/generic/test_environment/main.tf, tofu/modules/generic/test_environment/variables.tf
- Updates the providers to the current latest
- Replaces security group rules and inline rules with `aws_vpc_security_group_ingress_rule` & `aws_vpc_security_group_egress_rule` 
- see https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group.html for context
- Added a new SG for ssh access, removed open access to ssh port
- Added common EC2 ranges to the ssh access SG
- Added support for allowing addresses managed by a VPC prefix list to the "allowed" ssh SG
- Made changes to reduce the flakiness of `install_k3s.sh` and `install_rke2.sh`
- Made ssh tunnels toggleable
Note: `create_tunnels` should still be set to true for the tester cluster (and probably upstream) for AWS Dart files because the changes needed to make the certificates valid for the …
=> Make the AWS module's network more secure

charts/k6-files/.helmignore, charts/k6-files/templates/configmap.yaml, cmd/dartboard/subcommands/deploy.go, cmd/dartboard/subcommands/load.go, internal/kubectl/kubectl.go
- modifies configmap.yaml template to account for new k6/ dir structure
- modifies load.go to account for new k6/ dir structure
- adds a TODO to load.go
- modifies internal/kubectl.go's k6Run() function to account for the new dir structure
- adds a `.helmignore` file to the k6-files chart to mitigate data size issues when uploading files to tester cluster
Closes: #96
=> Fix broken `dartboard load` command

tofu/modules/generic/test_environment/main.tf, tofu/modules/generic/test_environment/variables.tf
There was no way to pass this to the modules, which already support it.
=> Add max_pods and node_cidr_mask_size to test environment downstream clusters
